name: Build

on:
  push:
    branches:
      - test

jobs:
  build_unix:

    runs-on: ubuntu-latest

    outputs:
      ytdlc_version: ${{ steps.bump_version.outputs.ytdlc_version }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      sha2_unix: ${{ steps.sha2_file.outputs.sha2_unix }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: '3.8'
    - name: Install packages
      run: sudo apt-get -y install zip pandoc man
    - name: Bump version
      id: bump_version
      run: python scripts/update-version-workflow.py
    - name: Check the output from My action
      run: echo "${{ steps.bump_version.outputs.ytdlc_version }}"
    - name: Run Make
      run: make
    - name: Install dependencies for pypi
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish on pypi
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        rm -rf dist/*
        python setup.py sdist bdist_wheel
        twine upload dist/*
